// This file was generated by gir (https://github.com/gtk-rs/gir)
// from lightdm-gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) LIGHTDM_GREETER_ERROR_COMMUNICATION_ERROR);
    PRINT_CONSTANT((gint) LIGHTDM_GREETER_ERROR_CONNECTION_FAILED);
    PRINT_CONSTANT((gint) LIGHTDM_GREETER_ERROR_INVALID_USER);
    PRINT_CONSTANT((gint) LIGHTDM_GREETER_ERROR_NO_AUTOLOGIN);
    PRINT_CONSTANT((gint) LIGHTDM_GREETER_ERROR_SESSION_FAILED);
    PRINT_CONSTANT(LIGHTDM_GREETER_SIGNAL_AUTHENTICATION_COMPLETE);
    PRINT_CONSTANT(LIGHTDM_GREETER_SIGNAL_AUTOLOGIN_TIMER_EXPIRED);
    PRINT_CONSTANT(LIGHTDM_GREETER_SIGNAL_IDLE);
    PRINT_CONSTANT(LIGHTDM_GREETER_SIGNAL_RESET);
    PRINT_CONSTANT(LIGHTDM_GREETER_SIGNAL_SHOW_MESSAGE);
    PRINT_CONSTANT(LIGHTDM_GREETER_SIGNAL_SHOW_PROMPT);
    PRINT_CONSTANT((gint) LIGHTDM_MESSAGE_TYPE_ERROR);
    PRINT_CONSTANT((gint) LIGHTDM_MESSAGE_TYPE_INFO);
    PRINT_CONSTANT((gint) LIGHTDM_PROMPT_TYPE_QUESTION);
    PRINT_CONSTANT((gint) LIGHTDM_PROMPT_TYPE_SECRET);
    PRINT_CONSTANT(LIGHTDM_SIGNAL_USER_CHANGED);
    PRINT_CONSTANT(LIGHTDM_USER_LIST_SIGNAL_USER_ADDED);
    PRINT_CONSTANT(LIGHTDM_USER_LIST_SIGNAL_USER_CHANGED);
    PRINT_CONSTANT(LIGHTDM_USER_LIST_SIGNAL_USER_REMOVED);
    return 0;
}
