// This file was generated by gir (https://github.com/gtk-rs/gir)
// from lightdm-gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "LightDMGreeter", sizeof(LightDMGreeter), alignof(LightDMGreeter));
    printf("%s;%zu;%zu\n", "LightDMGreeterClass", sizeof(LightDMGreeterClass), alignof(LightDMGreeterClass));
    printf("%s;%zu;%zu\n", "LightDMGreeterError", sizeof(LightDMGreeterError), alignof(LightDMGreeterError));
    printf("%s;%zu;%zu\n", "LightDMLanguage", sizeof(LightDMLanguage), alignof(LightDMLanguage));
    printf("%s;%zu;%zu\n", "LightDMLanguageClass", sizeof(LightDMLanguageClass), alignof(LightDMLanguageClass));
    printf("%s;%zu;%zu\n", "LightDMLayout", sizeof(LightDMLayout), alignof(LightDMLayout));
    printf("%s;%zu;%zu\n", "LightDMLayoutClass", sizeof(LightDMLayoutClass), alignof(LightDMLayoutClass));
    printf("%s;%zu;%zu\n", "LightDMMessageType", sizeof(LightDMMessageType), alignof(LightDMMessageType));
    printf("%s;%zu;%zu\n", "LightDMPromptType", sizeof(LightDMPromptType), alignof(LightDMPromptType));
    printf("%s;%zu;%zu\n", "LightDMSession", sizeof(LightDMSession), alignof(LightDMSession));
    printf("%s;%zu;%zu\n", "LightDMSessionClass", sizeof(LightDMSessionClass), alignof(LightDMSessionClass));
    printf("%s;%zu;%zu\n", "LightDMUser", sizeof(LightDMUser), alignof(LightDMUser));
    printf("%s;%zu;%zu\n", "LightDMUserClass", sizeof(LightDMUserClass), alignof(LightDMUserClass));
    printf("%s;%zu;%zu\n", "LightDMUserList", sizeof(LightDMUserList), alignof(LightDMUserList));
    printf("%s;%zu;%zu\n", "LightDMUserListClass", sizeof(LightDMUserListClass), alignof(LightDMUserListClass));
    return 0;
}
