// This file was generated by gir (https://github.com/gtk-rs/gir)
// from lightdm-gir-files
// DO NOT EDIT

use crate::ffi;
use glib::GStr;

#[doc(alias = "LIGHTDM_GREETER_SIGNAL_AUTHENTICATION_COMPLETE")]
pub static GREETER_SIGNAL_AUTHENTICATION_COMPLETE: &GStr = unsafe {
    GStr::from_utf8_with_nul_unchecked(ffi::LIGHTDM_GREETER_SIGNAL_AUTHENTICATION_COMPLETE)
};
#[doc(alias = "LIGHTDM_GREETER_SIGNAL_AUTOLOGIN_TIMER_EXPIRED")]
pub static GREETER_SIGNAL_AUTOLOGIN_TIMER_EXPIRED: &GStr = unsafe {
    GStr::from_utf8_with_nul_unchecked(ffi::LIGHTDM_GREETER_SIGNAL_AUTOLOGIN_TIMER_EXPIRED)
};
#[doc(alias = "LIGHTDM_GREETER_SIGNAL_IDLE")]
pub static GREETER_SIGNAL_IDLE: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::LIGHTDM_GREETER_SIGNAL_IDLE) };
#[doc(alias = "LIGHTDM_GREETER_SIGNAL_RESET")]
pub static GREETER_SIGNAL_RESET: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::LIGHTDM_GREETER_SIGNAL_RESET) };
#[doc(alias = "LIGHTDM_GREETER_SIGNAL_SHOW_MESSAGE")]
pub static GREETER_SIGNAL_SHOW_MESSAGE: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::LIGHTDM_GREETER_SIGNAL_SHOW_MESSAGE) };
#[doc(alias = "LIGHTDM_GREETER_SIGNAL_SHOW_PROMPT")]
pub static GREETER_SIGNAL_SHOW_PROMPT: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::LIGHTDM_GREETER_SIGNAL_SHOW_PROMPT) };
#[doc(alias = "LIGHTDM_SIGNAL_USER_CHANGED")]
pub static SIGNAL_USER_CHANGED: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::LIGHTDM_SIGNAL_USER_CHANGED) };
#[doc(alias = "LIGHTDM_USER_LIST_SIGNAL_USER_ADDED")]
pub static USER_LIST_SIGNAL_USER_ADDED: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::LIGHTDM_USER_LIST_SIGNAL_USER_ADDED) };
#[doc(alias = "LIGHTDM_USER_LIST_SIGNAL_USER_CHANGED")]
pub static USER_LIST_SIGNAL_USER_CHANGED: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::LIGHTDM_USER_LIST_SIGNAL_USER_CHANGED) };
#[doc(alias = "LIGHTDM_USER_LIST_SIGNAL_USER_REMOVED")]
pub static USER_LIST_SIGNAL_USER_REMOVED: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::LIGHTDM_USER_LIST_SIGNAL_USER_REMOVED) };
