// This file was generated by gir (https://github.com/gtk-rs/gir)
// from lightdm-gir-files
// DO NOT EDIT

use crate::{Language, Layout, Session, ffi};
use glib::{prelude::*, translate::*};

#[doc(alias = "lightdm_get_can_hibernate")]
#[doc(alias = "get_can_hibernate")]
pub fn can_hibernate() -> bool {
    assert_initialized_main_thread!();
    unsafe { from_glib(ffi::lightdm_get_can_hibernate()) }
}

#[doc(alias = "lightdm_get_can_restart")]
#[doc(alias = "get_can_restart")]
pub fn can_restart() -> bool {
    assert_initialized_main_thread!();
    unsafe { from_glib(ffi::lightdm_get_can_restart()) }
}

#[doc(alias = "lightdm_get_can_shutdown")]
#[doc(alias = "get_can_shutdown")]
pub fn can_shutdown() -> bool {
    assert_initialized_main_thread!();
    unsafe { from_glib(ffi::lightdm_get_can_shutdown()) }
}

#[doc(alias = "lightdm_get_can_suspend")]
#[doc(alias = "get_can_suspend")]
pub fn can_suspend() -> bool {
    assert_initialized_main_thread!();
    unsafe { from_glib(ffi::lightdm_get_can_suspend()) }
}

#[doc(alias = "lightdm_get_hostname")]
#[doc(alias = "get_hostname")]
pub fn hostname() -> Option<glib::GString> {
    assert_initialized_main_thread!();
    unsafe { from_glib_none(ffi::lightdm_get_hostname()) }
}

#[doc(alias = "lightdm_get_language")]
#[doc(alias = "get_language")]
pub fn language() -> Option<Language> {
    assert_initialized_main_thread!();
    unsafe { from_glib_none(ffi::lightdm_get_language()) }
}

#[doc(alias = "lightdm_get_languages")]
#[doc(alias = "get_languages")]
pub fn languages() -> Vec<Language> {
    assert_initialized_main_thread!();
    unsafe { FromGlibPtrContainer::from_glib_none(ffi::lightdm_get_languages()) }
}

#[doc(alias = "lightdm_get_layout")]
#[doc(alias = "get_layout")]
pub fn layout() -> Option<Layout> {
    assert_initialized_main_thread!();
    unsafe { from_glib_none(ffi::lightdm_get_layout()) }
}

#[doc(alias = "lightdm_get_layouts")]
#[doc(alias = "get_layouts")]
pub fn layouts() -> Vec<Layout> {
    assert_initialized_main_thread!();
    unsafe { FromGlibPtrContainer::from_glib_none(ffi::lightdm_get_layouts()) }
}

#[doc(alias = "lightdm_get_motd")]
#[doc(alias = "get_motd")]
pub fn motd() -> Option<glib::GString> {
    assert_initialized_main_thread!();
    unsafe { from_glib_full(ffi::lightdm_get_motd()) }
}

#[doc(alias = "lightdm_get_os_id")]
#[doc(alias = "get_os_id")]
pub fn os_id() -> Option<glib::GString> {
    assert_initialized_main_thread!();
    unsafe { from_glib_none(ffi::lightdm_get_os_id()) }
}

#[doc(alias = "lightdm_get_os_name")]
#[doc(alias = "get_os_name")]
pub fn os_name() -> Option<glib::GString> {
    assert_initialized_main_thread!();
    unsafe { from_glib_none(ffi::lightdm_get_os_name()) }
}

#[doc(alias = "lightdm_get_os_pretty_name")]
#[doc(alias = "get_os_pretty_name")]
pub fn os_pretty_name() -> Option<glib::GString> {
    assert_initialized_main_thread!();
    unsafe { from_glib_none(ffi::lightdm_get_os_pretty_name()) }
}

#[doc(alias = "lightdm_get_os_version")]
#[doc(alias = "get_os_version")]
pub fn os_version() -> Option<glib::GString> {
    assert_initialized_main_thread!();
    unsafe { from_glib_none(ffi::lightdm_get_os_version()) }
}

#[doc(alias = "lightdm_get_os_version_id")]
#[doc(alias = "get_os_version_id")]
pub fn os_version_id() -> Option<glib::GString> {
    assert_initialized_main_thread!();
    unsafe { from_glib_none(ffi::lightdm_get_os_version_id()) }
}

#[doc(alias = "lightdm_get_remote_sessions")]
#[doc(alias = "get_remote_sessions")]
pub fn remote_sessions() -> Vec<Session> {
    assert_initialized_main_thread!();
    unsafe { FromGlibPtrContainer::from_glib_none(ffi::lightdm_get_remote_sessions()) }
}

#[doc(alias = "lightdm_get_sessions")]
#[doc(alias = "get_sessions")]
pub fn sessions() -> Vec<Session> {
    assert_initialized_main_thread!();
    unsafe { FromGlibPtrContainer::from_glib_none(ffi::lightdm_get_sessions()) }
}

#[doc(alias = "lightdm_hibernate")]
pub fn hibernate() -> Result<(), glib::Error> {
    assert_initialized_main_thread!();
    unsafe {
        let mut error = std::ptr::null_mut();
        let is_ok = ffi::lightdm_hibernate(&mut error);
        debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
        if error.is_null() {
            Ok(())
        } else {
            Err(from_glib_full(error))
        }
    }
}

#[doc(alias = "lightdm_restart")]
pub fn restart() -> Result<(), glib::Error> {
    assert_initialized_main_thread!();
    unsafe {
        let mut error = std::ptr::null_mut();
        let is_ok = ffi::lightdm_restart(&mut error);
        debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
        if error.is_null() {
            Ok(())
        } else {
            Err(from_glib_full(error))
        }
    }
}

#[doc(alias = "lightdm_set_layout")]
pub fn set_layout(layout: &impl IsA<Layout>) {
    skip_assert_initialized!();
    unsafe {
        ffi::lightdm_set_layout(layout.as_ref().to_glib_none().0);
    }
}

#[doc(alias = "lightdm_shutdown")]
pub fn shutdown() -> Result<(), glib::Error> {
    assert_initialized_main_thread!();
    unsafe {
        let mut error = std::ptr::null_mut();
        let is_ok = ffi::lightdm_shutdown(&mut error);
        debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
        if error.is_null() {
            Ok(())
        } else {
            Err(from_glib_full(error))
        }
    }
}

#[doc(alias = "lightdm_suspend")]
pub fn suspend() -> Result<(), glib::Error> {
    assert_initialized_main_thread!();
    unsafe {
        let mut error = std::ptr::null_mut();
        let is_ok = ffi::lightdm_suspend(&mut error);
        debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
        if error.is_null() {
            Ok(())
        } else {
            Err(from_glib_full(error))
        }
    }
}
