// This file was generated by gir (https://github.com/gtk-rs/gir)
// from lightdm-gir-files
// DO NOT EDIT

use crate::{Language, Layout, Session, ffi};
use glib::{prelude::*, translate::*};

/// Checks if is authorized to do a system hibernate.
///
/// # Returns
///
/// [`true`] if can hibernate the system
#[doc(alias = "lightdm_get_can_hibernate")]
#[doc(alias = "get_can_hibernate")]
pub fn can_hibernate() -> bool {
    assert_initialized_main_thread!();
    unsafe { from_glib(ffi::lightdm_get_can_hibernate()) }
}

/// Checks if is authorized to do a system restart.
///
/// # Returns
///
/// [`true`] if can restart the system
#[doc(alias = "lightdm_get_can_restart")]
#[doc(alias = "get_can_restart")]
pub fn can_restart() -> bool {
    assert_initialized_main_thread!();
    unsafe { from_glib(ffi::lightdm_get_can_restart()) }
}

/// Checks if is authorized to do a system shutdown.
///
/// # Returns
///
/// [`true`] if can shutdown the system
#[doc(alias = "lightdm_get_can_shutdown")]
#[doc(alias = "get_can_shutdown")]
pub fn can_shutdown() -> bool {
    assert_initialized_main_thread!();
    unsafe { from_glib(ffi::lightdm_get_can_shutdown()) }
}

/// Checks if authorized to do a system suspend.
///
/// # Returns
///
/// [`true`] if can suspend the system
#[doc(alias = "lightdm_get_can_suspend")]
#[doc(alias = "get_can_suspend")]
pub fn can_suspend() -> bool {
    assert_initialized_main_thread!();
    unsafe { from_glib(ffi::lightdm_get_can_suspend()) }
}

///
/// # Returns
///
/// The name of the host we are running on.
#[doc(alias = "lightdm_get_hostname")]
#[doc(alias = "get_hostname")]
pub fn hostname() -> Option<glib::GString> {
    assert_initialized_main_thread!();
    unsafe { from_glib_none(ffi::lightdm_get_hostname()) }
}

/// Get the current language.
///
/// # Returns
///
/// The current language or [`None`] if no language.
#[doc(alias = "lightdm_get_language")]
#[doc(alias = "get_language")]
pub fn language() -> Option<Language> {
    assert_initialized_main_thread!();
    unsafe { from_glib_none(ffi::lightdm_get_language()) }
}

/// Get a list of languages to present to the user.
///
/// # Returns
///
/// A list of [`Language`][crate::Language] that should be presented to the user.
#[doc(alias = "lightdm_get_languages")]
#[doc(alias = "get_languages")]
pub fn languages() -> Vec<Language> {
    assert_initialized_main_thread!();
    unsafe { FromGlibPtrContainer::from_glib_none(ffi::lightdm_get_languages()) }
}

/// Get the current keyboard layout.
///
/// # Returns
///
/// The currently active layout for this user.
#[doc(alias = "lightdm_get_layout")]
#[doc(alias = "get_layout")]
pub fn layout() -> Option<Layout> {
    assert_initialized_main_thread!();
    unsafe { from_glib_none(ffi::lightdm_get_layout()) }
}

/// Get a list of keyboard layouts to present to the user.
///
/// # Returns
///
/// A list of [`Layout`][crate::Layout] that should be presented to the user.
#[doc(alias = "lightdm_get_layouts")]
#[doc(alias = "get_layouts")]
pub fn layouts() -> Vec<Layout> {
    assert_initialized_main_thread!();
    unsafe { FromGlibPtrContainer::from_glib_none(ffi::lightdm_get_layouts()) }
}

/// Get a system message that should be presented to the user.
/// e.g. "Welcome to Yoyodyne"
///
/// # Returns
///
/// a string (the contents of /etc/motd) or [`None`] if not set.
#[doc(alias = "lightdm_get_motd")]
#[doc(alias = "get_motd")]
pub fn motd() -> Option<glib::GString> {
    assert_initialized_main_thread!();
    unsafe { from_glib_full(ffi::lightdm_get_motd()) }
}

/// Get a word describing the OS, suitable for checking which OS the greeter is running on.
/// e.g. "ubuntu"
///
/// # Returns
///
/// a string (ID variable from /etc/os-release) or [`None`] if not set.
#[doc(alias = "lightdm_get_os_id")]
#[doc(alias = "get_os_id")]
pub fn os_id() -> Option<glib::GString> {
    assert_initialized_main_thread!();
    unsafe { from_glib_none(ffi::lightdm_get_os_id()) }
}

/// Get a line of text describing the OS without version information, suitable for presentation to the user.
/// e.g. "Ubuntu"
///
/// # Returns
///
/// a string (NAME variable from /etc/os-release) or [`None`] if not set.
#[doc(alias = "lightdm_get_os_name")]
#[doc(alias = "get_os_name")]
pub fn os_name() -> Option<glib::GString> {
    assert_initialized_main_thread!();
    unsafe { from_glib_none(ffi::lightdm_get_os_name()) }
}

/// Get a line of text describing the OS, suitable for presentation to the user.
/// e.g. "Ubuntu 16.04.1 LTS"
///
/// # Returns
///
/// a string (PRETTY_NAME variable from /etc/os-release) or [`None`] if not set.
#[doc(alias = "lightdm_get_os_pretty_name")]
#[doc(alias = "get_os_pretty_name")]
pub fn os_pretty_name() -> Option<glib::GString> {
    assert_initialized_main_thread!();
    unsafe { from_glib_none(ffi::lightdm_get_os_pretty_name()) }
}

/// Get a line of text describing the OS version, suitable for presentation to the user.
/// e.g. "16.04.1 LTS (Xenial Xapus)"
///
/// # Returns
///
/// a string (VERSION variable from /etc/os-release) or [`None`] if not set.
#[doc(alias = "lightdm_get_os_version")]
#[doc(alias = "get_os_version")]
pub fn os_version() -> Option<glib::GString> {
    assert_initialized_main_thread!();
    unsafe { from_glib_none(ffi::lightdm_get_os_version()) }
}

/// Get a word descibing the OS version, suitable for checking which version of the OS this greeter is running on.
/// e.g. "16.04"
///
/// # Returns
///
/// a string (VERSION_ID variable from /etc/os-release) or [`None`] if not set.
#[doc(alias = "lightdm_get_os_version_id")]
#[doc(alias = "get_os_version_id")]
pub fn os_version_id() -> Option<glib::GString> {
    assert_initialized_main_thread!();
    unsafe { from_glib_none(ffi::lightdm_get_os_version_id()) }
}

/// Get the available remote sessions.
///
/// # Returns
///
/// A list of [`Session`][crate::Session]
#[doc(alias = "lightdm_get_remote_sessions")]
#[doc(alias = "get_remote_sessions")]
pub fn remote_sessions() -> Vec<Session> {
    assert_initialized_main_thread!();
    unsafe { FromGlibPtrContainer::from_glib_none(ffi::lightdm_get_remote_sessions()) }
}

/// Get the available sessions.
///
/// # Returns
///
/// A list of [`Session`][crate::Session]
#[doc(alias = "lightdm_get_sessions")]
#[doc(alias = "get_sessions")]
pub fn sessions() -> Vec<Session> {
    assert_initialized_main_thread!();
    unsafe { FromGlibPtrContainer::from_glib_none(ffi::lightdm_get_sessions()) }
}

/// Triggers a system hibernate.
///
/// # Returns
///
/// [`true`] if hibernate initiated.
#[doc(alias = "lightdm_hibernate")]
pub fn hibernate() -> Result<(), glib::Error> {
    assert_initialized_main_thread!();
    unsafe {
        let mut error = std::ptr::null_mut();
        let is_ok = ffi::lightdm_hibernate(&mut error);
        debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
        if error.is_null() {
            Ok(())
        } else {
            Err(from_glib_full(error))
        }
    }
}

/// Triggers a system restart.
///
/// # Returns
///
/// [`true`] if restart initiated.
#[doc(alias = "lightdm_restart")]
pub fn restart() -> Result<(), glib::Error> {
    assert_initialized_main_thread!();
    unsafe {
        let mut error = std::ptr::null_mut();
        let is_ok = ffi::lightdm_restart(&mut error);
        debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
        if error.is_null() {
            Ok(())
        } else {
            Err(from_glib_full(error))
        }
    }
}

/// Set the layout for this session.
/// ## `layout`
/// The layout to use
#[doc(alias = "lightdm_set_layout")]
pub fn set_layout(layout: &impl IsA<Layout>) {
    skip_assert_initialized!();
    unsafe {
        ffi::lightdm_set_layout(layout.as_ref().to_glib_none().0);
    }
}

/// Triggers a system shutdown.
///
/// # Returns
///
/// [`true`] if shutdown initiated.
#[doc(alias = "lightdm_shutdown")]
pub fn shutdown() -> Result<(), glib::Error> {
    assert_initialized_main_thread!();
    unsafe {
        let mut error = std::ptr::null_mut();
        let is_ok = ffi::lightdm_shutdown(&mut error);
        debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
        if error.is_null() {
            Ok(())
        } else {
            Err(from_glib_full(error))
        }
    }
}

/// Triggers a system suspend.
///
/// # Returns
///
/// [`true`] if suspend initiated.
#[doc(alias = "lightdm_suspend")]
pub fn suspend() -> Result<(), glib::Error> {
    assert_initialized_main_thread!();
    unsafe {
        let mut error = std::ptr::null_mut();
        let is_ok = ffi::lightdm_suspend(&mut error);
        debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
        if error.is_null() {
            Ok(())
        } else {
            Err(from_glib_full(error))
        }
    }
}
