// This file was generated by gir (https://github.com/gtk-rs/gir)
// from lightdm-gir-files
// DO NOT EDIT

use crate::ffi;
use glib::{
    prelude::*,
    signal::{SignalHandlerId, connect_raw},
    translate::*,
};
use std::boxed::Box as Box_;

glib::wrapper! {
    /// [`Language`][crate::Language] is an opaque data structure and can only be accessed
    /// using the provided functions.
    ///
    /// ## Properties
    ///
    ///
    /// #### `code`
    ///  Readable | Writeable | Construct Only
    ///
    ///
    /// #### `name`
    ///  Readable
    ///
    ///
    /// #### `territory`
    ///  Readable
    ///
    /// # Implements
    ///
    /// [`LanguageExt`][trait@crate::prelude::LanguageExt]
    #[doc(alias = "LightDMLanguage")]
    pub struct Language(Object<ffi::LightDMLanguage, ffi::LightDMLanguageClass>);

    match fn {
        type_ => || ffi::lightdm_language_get_type(),
    }
}

impl Language {
    pub const NONE: Option<&'static Language> = None;

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`Language`] objects.
    ///
    /// This method returns an instance of [`LanguageBuilder`](crate::builders::LanguageBuilder) which can be used to create [`Language`] objects.
    pub fn builder() -> LanguageBuilder {
        LanguageBuilder::new()
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`Language`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct LanguageBuilder {
    builder: glib::object::ObjectBuilder<'static, Language>,
}

impl LanguageBuilder {
    fn new() -> Self {
        Self {
            builder: glib::object::Object::builder(),
        }
    }

    pub fn code(self, code: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("code", code.into()),
        }
    }

    // rustdoc-stripper-ignore-next
    /// Build the [`Language`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> Language {
        assert_initialized_main_thread!();
        self.builder.build()
    }
}

/// Trait containing all [`struct@Language`] methods.
///
/// # Implementors
///
/// [`Language`][struct@crate::Language]
pub trait LanguageExt: IsA<Language> + 'static {
    /// Get the code of a language (e.g. "de_DE.UTF-8")
    ///
    /// # Returns
    ///
    /// The code of the language
    #[doc(alias = "lightdm_language_get_code")]
    #[doc(alias = "get_code")]
    fn code(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_language_get_code(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    /// Get the name of a language.
    ///
    /// # Returns
    ///
    /// The name of the language
    #[doc(alias = "lightdm_language_get_name")]
    #[doc(alias = "get_name")]
    fn name(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_language_get_name(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    /// Get the territory the language is used in.
    ///
    /// # Returns
    ///
    /// The territory the language is used in.
    #[doc(alias = "lightdm_language_get_territory")]
    #[doc(alias = "get_territory")]
    fn territory(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_language_get_territory(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    /// Check if a language code matches this language.
    /// ## `code`
    /// A language code
    ///
    /// # Returns
    ///
    /// [`true`] if the code matches this language.
    #[doc(alias = "lightdm_language_matches")]
    fn matches(&self, code: &str) -> bool {
        unsafe {
            from_glib(ffi::lightdm_language_matches(
                self.as_ref().to_glib_none().0,
                code.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "name")]
    fn connect_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_name_trampoline<P: IsA<Language>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMLanguage,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Language::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::name".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_name_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "territory")]
    fn connect_territory_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_territory_trampoline<P: IsA<Language>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMLanguage,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Language::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::territory".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_territory_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl<O: IsA<Language>> LanguageExt for O {}
