// This file was generated by gir (https://github.com/gtk-rs/gir)
// from lightdm-gir-files
// DO NOT EDIT

use crate::ffi;
use glib::{prelude::*, translate::*};

glib::wrapper! {
    /// [`Layout`][crate::Layout] is an opaque data structure and can only be accessed
    /// using the provided functions.
    ///
    /// ## Properties
    ///
    ///
    /// #### `description`
    ///  Readable | Writeable | Construct Only
    ///
    ///
    /// #### `name`
    ///  Readable | Writeable | Construct Only
    ///
    ///
    /// #### `short-description`
    ///  Readable | Writeable | Construct Only
    ///
    /// # Implements
    ///
    /// [`LayoutExt`][trait@crate::prelude::LayoutExt]
    #[doc(alias = "LightDMLayout")]
    pub struct Layout(Object<ffi::LightDMLayout, ffi::LightDMLayoutClass>);

    match fn {
        type_ => || ffi::lightdm_layout_get_type(),
    }
}

impl Layout {
    pub const NONE: Option<&'static Layout> = None;

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`Layout`] objects.
    ///
    /// This method returns an instance of [`LayoutBuilder`](crate::builders::LayoutBuilder) which can be used to create [`Layout`] objects.
    pub fn builder() -> LayoutBuilder {
        LayoutBuilder::new()
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`Layout`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct LayoutBuilder {
    builder: glib::object::ObjectBuilder<'static, Layout>,
}

impl LayoutBuilder {
    fn new() -> Self {
        Self {
            builder: glib::object::Object::builder(),
        }
    }

    pub fn description(self, description: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("description", description.into()),
        }
    }

    pub fn name(self, name: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("name", name.into()),
        }
    }

    pub fn short_description(self, short_description: impl Into<glib::GString>) -> Self {
        Self {
            builder: self
                .builder
                .property("short-description", short_description.into()),
        }
    }

    // rustdoc-stripper-ignore-next
    /// Build the [`Layout`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> Layout {
        assert_initialized_main_thread!();
        self.builder.build()
    }
}

/// Trait containing all [`struct@Layout`] methods.
///
/// # Implementors
///
/// [`Layout`][struct@crate::Layout]
pub trait LayoutExt: IsA<Layout> + 'static {
    /// Get the long description of a layout.
    ///
    /// # Returns
    ///
    /// A long description of the layout
    #[doc(alias = "lightdm_layout_get_description")]
    #[doc(alias = "get_description")]
    fn description(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_layout_get_description(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    /// Get the name of a layout.
    ///
    /// # Returns
    ///
    /// The name of the layout
    #[doc(alias = "lightdm_layout_get_name")]
    #[doc(alias = "get_name")]
    fn name(&self) -> Option<glib::GString> {
        unsafe { from_glib_none(ffi::lightdm_layout_get_name(self.as_ref().to_glib_none().0)) }
    }

    /// Get the short description of a layout.
    ///
    /// # Returns
    ///
    /// A short description of the layout
    #[doc(alias = "lightdm_layout_get_short_description")]
    #[doc(alias = "get_short_description")]
    #[doc(alias = "short-description")]
    fn short_description(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_layout_get_short_description(
                self.as_ref().to_glib_none().0,
            ))
        }
    }
}

impl<O: IsA<Layout>> LayoutExt for O {}
