// This file was generated by gir (https://github.com/gtk-rs/gir)
// from lightdm-gir-files
// DO NOT EDIT

use crate::ffi;
use glib::{
    prelude::*,
    signal::{SignalHandlerId, connect_raw},
    translate::*,
};
use std::boxed::Box as Box_;

glib::wrapper! {
    /// [`Session`][crate::Session] is an opaque data structure and can only be accessed
    /// using the provided functions.
    ///
    /// ## Properties
    ///
    ///
    /// #### `comment`
    ///  Readable
    ///
    ///
    /// #### `key`
    ///  Readable
    ///
    ///
    /// #### `name`
    ///  Readable
    ///
    /// # Implements
    ///
    /// [`SessionExt`][trait@crate::prelude::SessionExt]
    #[doc(alias = "LightDMSession")]
    pub struct Session(Object<ffi::LightDMSession, ffi::LightDMSessionClass>);

    match fn {
        type_ => || ffi::lightdm_session_get_type(),
    }
}

impl Session {
    pub const NONE: Option<&'static Session> = None;
}

/// Trait containing all [`struct@Session`] methods.
///
/// # Implementors
///
/// [`Session`][struct@crate::Session]
pub trait SessionExt: IsA<Session> + 'static {
    /// Get the comment for a session
    ///
    /// # Returns
    ///
    /// The session comment
    #[doc(alias = "lightdm_session_get_comment")]
    #[doc(alias = "get_comment")]
    fn comment(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_session_get_comment(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    /// Get the key for a session
    ///
    /// # Returns
    ///
    /// The session key
    #[doc(alias = "lightdm_session_get_key")]
    #[doc(alias = "get_key")]
    fn key(&self) -> Option<glib::GString> {
        unsafe { from_glib_none(ffi::lightdm_session_get_key(self.as_ref().to_glib_none().0)) }
    }

    /// Get the name for a session
    ///
    /// # Returns
    ///
    /// The session name
    #[doc(alias = "lightdm_session_get_name")]
    #[doc(alias = "get_name")]
    fn name(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_session_get_name(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    /// Get the type a session
    ///
    /// # Returns
    ///
    /// The session type, e.g. x or mir
    #[doc(alias = "lightdm_session_get_session_type")]
    #[doc(alias = "get_session_type")]
    fn session_type(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_session_get_session_type(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "comment")]
    fn connect_comment_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_comment_trampoline<P: IsA<Session>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMSession,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Session::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::comment".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_comment_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "key")]
    fn connect_key_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_key_trampoline<P: IsA<Session>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMSession,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Session::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::key".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_key_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "name")]
    fn connect_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_name_trampoline<P: IsA<Session>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMSession,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Session::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::name".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_name_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl<O: IsA<Session>> SessionExt for O {}
