// This file was generated by gir (https://github.com/gtk-rs/gir)
// from lightdm-gir-files
// DO NOT EDIT

use crate::ffi;
use glib::{
    object::ObjectType as _,
    prelude::*,
    signal::{SignalHandlerId, connect_raw},
    translate::*,
};
use std::boxed::Box as Box_;

glib::wrapper! {
    #[doc(alias = "LightDMUser")]
    pub struct User(Object<ffi::LightDMUser, ffi::LightDMUserClass>);

    match fn {
        type_ => || ffi::lightdm_user_get_type(),
    }
}

impl User {
    pub const NONE: Option<&'static User> = None;
}

pub trait UserExt: IsA<User> + 'static {
    #[doc(alias = "lightdm_user_get_background")]
    #[doc(alias = "get_background")]
    fn background(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_user_get_background(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "lightdm_user_get_display_name")]
    #[doc(alias = "get_display_name")]
    #[doc(alias = "display-name")]
    fn display_name(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_user_get_display_name(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "lightdm_user_get_has_messages")]
    #[doc(alias = "get_has_messages")]
    #[doc(alias = "has-messages")]
    fn has_messages(&self) -> bool {
        unsafe {
            from_glib(ffi::lightdm_user_get_has_messages(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "lightdm_user_get_home_directory")]
    #[doc(alias = "get_home_directory")]
    #[doc(alias = "home-directory")]
    fn home_directory(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_user_get_home_directory(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "lightdm_user_get_image")]
    #[doc(alias = "get_image")]
    fn image(&self) -> Option<glib::GString> {
        unsafe { from_glib_none(ffi::lightdm_user_get_image(self.as_ref().to_glib_none().0)) }
    }

    #[doc(alias = "lightdm_user_get_is_locked")]
    #[doc(alias = "get_is_locked")]
    #[doc(alias = "is-locked")]
    fn is_locked(&self) -> bool {
        unsafe {
            from_glib(ffi::lightdm_user_get_is_locked(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "lightdm_user_get_language")]
    #[doc(alias = "get_language")]
    fn language(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_user_get_language(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "lightdm_user_get_layout")]
    #[doc(alias = "get_layout")]
    fn layout(&self) -> Option<glib::GString> {
        unsafe { from_glib_none(ffi::lightdm_user_get_layout(self.as_ref().to_glib_none().0)) }
    }

    #[doc(alias = "lightdm_user_get_layouts")]
    #[doc(alias = "get_layouts")]
    fn layouts(&self) -> Vec<glib::GString> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::lightdm_user_get_layouts(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "lightdm_user_get_logged_in")]
    #[doc(alias = "get_logged_in")]
    #[doc(alias = "logged-in")]
    fn is_logged_in(&self) -> bool {
        unsafe {
            from_glib(ffi::lightdm_user_get_logged_in(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "lightdm_user_get_name")]
    #[doc(alias = "get_name")]
    fn name(&self) -> Option<glib::GString> {
        unsafe { from_glib_none(ffi::lightdm_user_get_name(self.as_ref().to_glib_none().0)) }
    }

    #[doc(alias = "lightdm_user_get_real_name")]
    #[doc(alias = "get_real_name")]
    #[doc(alias = "real-name")]
    fn real_name(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_user_get_real_name(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "lightdm_user_get_session")]
    #[doc(alias = "get_session")]
    fn session(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_user_get_session(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "lightdm_user_get_uid")]
    #[doc(alias = "get_uid")]
    fn uid(&self) -> u32 {
        unsafe { ffi::lightdm_user_get_uid(self.as_ref().to_glib_none().0) }
    }

    #[doc(alias = "changed")]
    fn connect_changed<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn changed_trampoline<P: IsA<User>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMUser,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(User::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"changed".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    changed_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "background")]
    fn connect_background_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_background_trampoline<P: IsA<User>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMUser,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(User::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::background".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_background_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "display-name")]
    fn connect_display_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_display_name_trampoline<P: IsA<User>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMUser,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(User::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::display-name".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_display_name_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "has-messages")]
    fn connect_has_messages_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_has_messages_trampoline<P: IsA<User>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMUser,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(User::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::has-messages".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_has_messages_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "home-directory")]
    fn connect_home_directory_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_home_directory_trampoline<P: IsA<User>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMUser,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(User::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::home-directory".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_home_directory_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "image")]
    fn connect_image_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_image_trampoline<P: IsA<User>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMUser,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(User::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::image".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_image_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "is-locked")]
    fn connect_is_locked_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_is_locked_trampoline<P: IsA<User>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMUser,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(User::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::is-locked".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_is_locked_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "language")]
    fn connect_language_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_language_trampoline<P: IsA<User>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMUser,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(User::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::language".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_language_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "layout")]
    fn connect_layout_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_layout_trampoline<P: IsA<User>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMUser,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(User::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::layout".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_layout_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "layouts")]
    fn connect_layouts_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_layouts_trampoline<P: IsA<User>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMUser,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(User::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::layouts".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_layouts_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "logged-in")]
    fn connect_logged_in_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_logged_in_trampoline<P: IsA<User>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMUser,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(User::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::logged-in".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_logged_in_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "name")]
    fn connect_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_name_trampoline<P: IsA<User>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMUser,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(User::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::name".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_name_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "real-name")]
    fn connect_real_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_real_name_trampoline<P: IsA<User>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMUser,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(User::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::real-name".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_real_name_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "session")]
    fn connect_session_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_session_trampoline<P: IsA<User>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMUser,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(User::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::session".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_session_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "uid")]
    fn connect_uid_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_uid_trampoline<P: IsA<User>, F: Fn(&P) + 'static>(
            this: *mut ffi::LightDMUser,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(User::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::uid".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_uid_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl<O: IsA<User>> UserExt for O {}
